### ISSUE TITLE
Sorting in mobile browser

### ISSUE THREAD

**Issue by gbcgit** [jrief/django-admin-sortable2#108]
Not sure if this is a bug, perhaps I isn't a feature yet, but I have a Django Admin page that I used on my phone - Android.  I have the sorting working on the desktop browser, Chrome.   On my phone, the sort area appears, but drag/drop to scroll, like on desktop, is not working at all.    I have tried Chroma and Opera mobile.

**Comment by jrief** [comment]
Hmmm, for this part I use [jquery-ui sortable](https://jqueryui.com/sortable/). Could you please google if there is a mobile version of this plugin.

**Comment by gbcgit** [comment]
Interesting, well, I went to that URL on my phone, and sure thing, it doesn't work there either.  Not sure if it should, but of course, this does look like an upstream issue, not one for your codebase.

**Comment by jrief** [comment]
Maybe in jquery mobile, there is a similar library, I'm not aware of.

**Comment by jrief** [comment]
Could you try out this and share your experience: http://touchpunch.furf.com/

**Comment by kimscheibel** [comment]
I tried http://touchpunch.furf.com/ on Chrome and Firefox on Android and the dragging functionality worked.

**Comment by jrief** [comment]
@kimscheibel does this mean, that by simply adding `<script src="jquery.ui.touch-punch.min.js"></script>` to the admin template, everything works? That would be awesome!

**Comment by GHPS** [comment]
> @kimscheibel does this mean, that by simply adding `<script src="jquery.ui.touch-punch.min.js"></script>` to the admin template, everything works?

Yes - it's rather simple - just link to jquery.ui.touch-punch (see PR #246) which
is a thin wrapper from touch UI to the mouse UI already in use.

I tested admin-sortable2 with these changes on Android. I works without any
issues on Chrome. 

Firefox (68.*), however, gets irritated by the space character used in the drag handle
of sortable2. It recognizes this as normal text and tries to be helpful by offering the 
copy-paste-insert dialog. Therefore dragging the item becomes impossible.

This is a shortcoming of sortable2 since the drag-and-drop examples on the
jquery.ui.touch-punch homepage run without any problem.

Perhaps the single space character could be replaced by an icon? The grey
background icon currently used to highlight the handle?

**Comment by jrief** [comment]
closed via #246
