### ISSUE TITLE
An invalid form control with name='page' is not focusable.

### ISSUE THREAD

**Issue by joseph2002** [jrief/django-admin-sortable2#113]
Chromium report this when I run delete selected action on SortableAdminMixin. 
I think this is caused by setting max=0 and min=2 to #changelist-form-page when there is only one page. By submitting, chromium find the form is invalid, but can not focus on the hidden #changelist-form-page field.

btw. I use grappelli, don't know whether it is ok for original admin

**Comment by jrief** [comment]
Grappelli changes the rendering templates quite at lot, that's one of the reasons it doesn't work well with djangoCMS.
Please retry without Grappelli and report your experience.

**Comment by fgmacedo** [comment]
I'm experiencing the same issue. It works without Grappelli. I'm trying to figure out what changes in order to break an action that does not have any relation with ordering.

**Comment by fgmacedo** [comment]
I found 2 issues:

1) With Grappelli, the `changelist-form` changes to `grp-changelist-form, so the js selector needs a update (TODO: find a generic selector):

    	$('#grp-changelist-form').find('select[name="action"]').change(function() {

2) The error message came from the browser trying to display the HTML5 validation of the field `changelist-form-page`, but cannot since it's hidden. The default Django template contains a `novalidate` attr on form.
