### ISSUE TITLE
Reverse Ordering

### ISSUE THREAD

**Issue by kayadata** [jrief/django-admin-sortable2#154]
Hi Jacob. 

Problem with reverse ordering doesn't seems to be resolved. #143 

Django==1.11.1
django-admin-sortable2==0.6.11

**Comment by jawinn** [comment]
I am also seeing a similar issue here. By default, it seems to be creating the numbers in reverse of how they are displayed in default ascending. I then tried changing the class order to descending `ordering = ('-order',)  `, similar to the linked issue, but in my model Meta. This caused the drag and drop ordering functionality to start putting things in unexpected places after refresh, which I guess is because it's reversed (??). I've put it back to ascending order, and have just had to do a descending orderby anywhere outside the admin where I'm querying.  

Django==1.10.7
django-admin-sortable2==0.6.14

**Comment by svleeuwen** [comment]
Experiencing this too. Especially when dragging from down in the list to the top most position.

This commit https://github.com/svleeuwen/django-admin-sortable2/commit/359b96250466f6d9d180a6dbf29e051348c75e9e fixes the issue, but I'm a bit worried it might break something else.

For example:
I see no more need for `default_order_directions` getting a different value when reverse ordering. At least not in `SortableAdminMixin`.
But it was also introduced on `CustomInlineFormSet` in this commit 634cfb1f6293cb7109f119658ed14832712fc5a6. I just don't see where that formset is using this.

**Comment by svleeuwen** [comment]
UPDATE:

Dug a little deeper and fixed all issues with reverse ordering in inline admin too.

See PR https://github.com/jrief/django-admin-sortable2/pull/173
