### ISSUE TITLE
django-mptt support

### ISSUE THREAD

**Issue by Senpos** [jrief/django-admin-sortable2#191]
Hello.

Is there a way to make `django-admin-sortable2` work with `django-mptt`?

They have different approach of ordering and use 
```
class MPTTMeta:
        order_insertion_by = ['name']
```
instead of 
```
class Meta:
    ordering = ('field',)
```
[described here](https://django-mptt.github.io/django-mptt/tutorial.html#set-up-your-model)

**Comment by jrief** [comment]
AFAIK, **django-mptt** uses jstree for sorting, which is the appropriate JS plugin to sort trees.

Anyway, I would not use django-mptt, but django-treebeard. Here we have an [open issue](https://github.com/django-treebeard/django-treebeard/issues/46) about adding sorting support using jstree. I would like to implement that in a similar way, as I did for django-admin-sortable2.

The reason this hasn't been addressed yet, is the lack of funding for this feature.

**Comment by jerch** [comment]
@jrief Where does django-mptt use jstree? Do you mean the change_list view? Imho this is a drilldown fork of FeinCMS's logic now included in the package.

I have build a very basic jstree based widget package for the admin (see https://github.com/jerch/django-treewidget), which tries to support sorting as well. It needs the help of ajax callbacks to get the tree information from the server since django's ugly popup window does not provide enough data to render it correctly on position or name changes. Sorting is not really tested, so there is much room left for improvements.

**Comment by jrief** [comment]
Trees are not handled by this app. Therefore I'm closing it.
