### ISSUE TITLE
use "django-admin-sortable2" in inlines hide "Add another ..." 

### ISSUE THREAD

**Issue by HosseinAssaran** [jrief/django-admin-sortable2#211]
I use this plugin to sort my inlines. 
The problem is:
Without use this plugin I see "Add another Chapter" without problem. Code below works well without this plugin 

```
class ChapterInline(admin.StackedInline):
    model = models.Chapter
    extra = 1
```

<img width="205" alt="screen shot 2018-10-18 at 12 26 03 pm" src="https://user-images.githubusercontent.com/26246084/47143006-13fac700-d2d1-11e8-86b5-85e32366f2e5.png">

 But when I add SortableInlineAdminMixin  as new input argument to ChapterInline in admin.py like below example, It hides "Add another  Chapter":

```
class ChapterInline(SortableInlineAdminMixin, admin.StackedInline):
    model = models.Chapter
    extra = 1
```

<img width="251" alt="screen shot 2018-10-18 at 12 27 37 pm" src="https://user-images.githubusercontent.com/26246084/47143074-3db3ee00-d2d1-11e8-9090-6e7d0d11e198.png">

I want to have both of them enable.  I want to be able to sort and also add another active in my project.
Please help me how can I solve this.

**Comment by pjdelport** [comment]
This appears to be due to a change in the signature of 

* Django 2.0.9 ([source](https://github.com/django/django/blob/2.0.9/django/contrib/admin/static/admin/js/inlines.js#L148)): `    $.fn.tabularFormset = function(options) …`
* Django 2.1 ([source](https://github.com/django/django/blob/2.1/django/contrib/admin/static/admin/js/inlines.js#L148)): `$.fn.tabularFormset = function(selector, options)`

`adminsortable2/js/inline-tabular.js` calls this function as `tabularFormset(config)`, which works in Django 2.0, but fails in 2.1: the `options` ends up being undefined, which ends up with a property access error.

**Comment by pjdelport** [comment]
Hmm, PRs #203 and #204 update the Django formset helper calls to be compatible with Django 2.1, but breaks it for earlier Django versions. 🙁
