### ISSUE TITLE
Silenced AttributeError for enable_sorting leads to bad list of admin media

### ISSUE THREAD

**Issue by stefanw** [jrief/django-admin-sortable2#50]
`enable_sorting` is set in [`get_changelist`](https://github.com/jrief/django-admin-sortable2/blob/master/adminsortable/admin.py#L103) and checked during gathering of `media`.

However, on the detail page `get_changelist` is not called and therefore accessing `enable_sorting` results in an `AttributeError` that is silenced by the media machinery (afaik). This somehow leads to bad media order (Django's jQuery not loaded on top, but in the middle of the stack). This results in JavaScript errors on the page.

A workaround is settings `enable_sorting = False` on your `ModelAdmin` subclass. But this should probably be set on the Mixin itself.

**Comment by a1tus** [comment]
This bug breaks admin widgets (like datepicker). Can be fixed easily by setting `enable_sorting` to False in __init__ method of `SortableAdminMixin`.

**Comment by trawick** [comment]
This change seems to address this issue: https://github.com/jrief/django-admin-sortable2/commit/4cc4dd5c936796371b52ddeebfc6ceb8fd744ae0

**Comment by trawick** [comment]
I'm seeing a much deeper issue with aldryn-faq+django-admin-sortable2 than just the Python attribute access problem (and I'm using version 0.6.0, which has a fix for that).

One instance of aldryn-faq's QuestionAdmin (which mixes in SortableAdminMixin) is used for both list view and detail view.  In list view, get_changelist is called and enable_sorting can be set.  In detail view, get_changelist is not called and, if list view has been loaded since server_restart, enable_sorting can still be True when SortableAdminMixin.media() is called.  It can then add list-sortable.js to the media for the response.

list-sortable.js bombs if adminsortable2's change_list.html hasn't been included, as it depends on some global variables defined in change_list.html (variables sortable_current_page and sortable_total_pages).  This in turn leads to other widgets failing to initialize.

Recap:

1. QuestionAdmin instance's enable_sorting attribute is set to True on a list view
2. still True when SortableAdminMixin.media() called on a detail view, so list-sortable.js added to media
3. when processing detail view page, browser starts running list-sortable.js code which blows up accessing global variables that are undefined (change_list.html, which defines the global variables, wasn't included)
4. browser aborts JS setup, leaving other widgets uninitialized

This is with Django 1.7.10 and Python 3.4.

**Comment by jrief** [comment]
@mkoistinen can you please check this. I never used aldryn-faq up to now

**Comment by jrief** [comment]
closed for inactivity
