### ISSUE TITLE
abstract model not saving positions

### ISSUE THREAD

**Issue by kuyucakli** [jrief/django-admin-sortable2#6]
I have a parent abstract class:
class Media(models.Model):  
    ...
    order = models.PositiveSmallIntegerField("Order", blank=False, null=False )

```
class Meta:
    abstract = True
```

and a child as:

class ModelImage(Media): 
    file = ImageField(upload_to=get_path) 
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey('content_type', 'object_id') 

```
class Meta:
    verbose_name = _('Image')
    verbose_name_plural = _('Images')
    ordering = ['order']  
```

When changed the position in admin order field is not updating ?  I am using django 1.6 with python 3.3... When not using abstract model everything works fine

**Comment by victor-yunenko** [comment]
Odd, I just stumbled into a very similar problem.

I got what [initial data](https://django-admin-sortable2.readthedocs.io/en/latest/usage.html#initial-data) is about, but what confused me is that I didn't need to run `python manage.py reorder` when I added it to a Model that had no abstract parent?

After the investigation I concluded that the only significant difference between the Model that I extended with sorting and which worked without the manage.py command, and the one that didn't work was the `abstract = True` parent.

I found that ticket because I started searching for `abstract` keyword.

Maybe it would be possible to add a django `messages.error("Please run python manage.py reorder")` on the reorder POST processing when the order is 0?
