### ISSUE TITLE
SortableInlineAdminMixin screws up TabularInline colums

### ISSUE THREAD

**Issue by max-pfeiffer** [jrief/django-admin-sortable2#82]
When combinig SortableInlineAdminMixin and TabularInline classes, the column titles doesn't match the column contents any more.

I seems that the content in the column after the "Sort" column is not rendered properly into the view. It is shifted one column further. See screenshot.

Using:
Django==1.8.7
django-admin-sortable2==0.6.2

![screen shot 2015-12-16 at 10 06 07](https://cloud.githubusercontent.com/assets/13573675/11836737/eee8508e-a3dc-11e5-870f-057251953aa2.png)

**Comment by jrief** [comment]
Could you please try using djangocms-admin-style. I use that all the time because it looks much nicer than Django's default style.
It is likely that I screwed up some CSS classes, because I always use djangocms-admin-style.

**Comment by madisvain** [comment]
I have the same issue on 1.9 and the admin actually looks quite good there.

**Comment by tsantor** [comment]
While this works, it doesn't render correctly when using Grappelli either.

**Comment by rubengrill** [comment]
This issue is also present when using djangocms-admin-style.
It happens when the order field is the first field (either because explicitly set in `fields` or because it is the first field in the model). In this case the django admin template for tabular inline does not render the first column with `colspan="2"`.
#107 Fixes this by ensuring that the order field is always on last position.

**Comment by jrief** [comment]
closed via #107
